on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  autobump:
    runs-on: macos-15
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@main
      - name: Cache Homebrew Bundler RubyGems
        id: cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.set-up-homebrew.outputs.gems-path }}
          key: ${{ runner.os }}-rubygems-${{ steps.set-up-homebrew.outputs.gems-hash }}
          restore-keys: ${{ runner.os }}-rubygems-
      
      - name: Install Homebrew Bundler RubyGems
        if: steps.cache.outputs.cache-hit != 'true'
        run: brew install-bundler-gems

      - name: Run `brew bump`
        env:
          GITHUB_TOKEN: ${{ github.token }}
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          brew bump --open-pr --no-fork --tap=bearbots6964/elastic-dashboard
